# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f53540ac7861fdf30c30fc3be4939971a3cd40f1d8af240174c3101ea5c272b99ea96042409d499479f2cd78b4d355b97c30251c22ef17353174da518701d20

test:
  secret_key_base: ee6d5ddba8ca78fc18c94dfa0bbefe66cdbb5fcc08221e76fb2f78b83dfafa4b2479c8768bab31a59ded5f1fb5f87cdf91454477c82ac189626b10de56ed3c75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
